[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.30.1"

[programs.localnet]
iamai_token = "ZfdsRp1fLCJJkqMmyfNst8nc85RDoCZq9bQbT2Cd3QQ"
iamai_staking = "Fa3w7XNsTzTqrJY1mUZ8QaorpDgMXqTWkYdtFn6GxjdP"
iamai_governance = "5kzjdRm4pHrTrqpijSB8QYE8tN9yCnmbHw49iX3DXc9y"
iamai_marketplace = "CDg2vpzshYKscaXa42PvP4PCKShWj6etDoyda86Fz47y"

[programs.devnet]
iamai_token = "ZfdsRp1fLCJJkqMmyfNst8nc85RDoCZq9bQbT2Cd3QQ"
iamai_staking = "Fa3w7XNsTzTqrJY1mUZ8QaorpDgMXqTWkYdtFn6GxjdP"
iamai_governance = "5kzjdRm4pHrTrqpijSB8QYE8tN9yCnmbHw49iX3DXc9y"
iamai_marketplace = "CDg2vpzshYKscaXa42PvP4PCKShWj6etDoyda86Fz47y"

[programs.mainnet]
iamai_token = "ZfdsRp1fLCJJkqMmyfNst8nc85RDoCZq9bQbT2Cd3QQ"
iamai_staking = "Fa3w7XNsTzTqrJY1mUZ8QaorpDgMXqTWkYdtFn6GxjdP"
iamai_governance = "5kzjdRm4pHrTrqpijSB8QYE8tN9yCnmbHw49iX3DXc9y"
iamai_marketplace = "CDg2vpzshYKscaXa42PvP4PCKShWj6etDoyda86Fz47y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "contracts/token",
    "contracts/staking", 
    "contracts/governance",
    "contracts/marketplace"
]
