[workspace]
resolver = "2"
members = [
    "contracts/token",
    "contracts/staking", 
    "contracts/governance",
    "contracts/marketplace"
]

[workspace.dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[profile.release]
overflow-checks = true
