[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SOLANA_NETWORK = "devnet"
  NEXT_PUBLIC_RPC_ENDPOINT = "https://api.devnet.solana.com"
  NEXT_PUBLIC_TOKEN_PROGRAM_ID = "F2iupsNmgY69NwD6a1ZETMhPPET8WLojYKDBbVCw72z2"
  NEXT_PUBLIC_STAKING_PROGRAM_ID = "HwSjU2QuDJjU7oLwrzue5RZ5Zcs1HHJPYbZFXGPTWfHg"
  NEXT_PUBLIC_GOVERNANCE_PROGRAM_ID = "HDLPuNmVXrVYCihhBqMshnQEfxXwugY6WCo9rWDWY4iH"
  NEXT_PUBLIC_MARKETPLACE_PROGRAM_ID = "3ASqWgGno8sQsmkihwkocjAk8gnscGoHzhLozZouPJEU"
  NEXT_PUBLIC_IAMAI_MINT_ADDRESS = "5ieP1Z14NwuJpWeanJWXLKBENwNzqMvXkwdLEC5kpfbu"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SOLANA_NETWORK = "devnet"
  NEXT_PUBLIC_RPC_ENDPOINT = "https://api.devnet.solana.com"
  NEXT_PUBLIC_TOKEN_PROGRAM_ID = "F2iupsNmgY69NwD6a1ZETMhPPET8WLojYKDBbVCw72z2"
  NEXT_PUBLIC_STAKING_PROGRAM_ID = "HwSjU2QuDJjU7oLwrzue5RZ5Zcs1HHJPYbZFXGPTWfHg"
  NEXT_PUBLIC_GOVERNANCE_PROGRAM_ID = "HDLPuNmVXrVYCihhBqMshnQEfxXwugY6WCo9rWDWY4iH"
  NEXT_PUBLIC_MARKETPLACE_PROGRAM_ID = "3ASqWgGno8sQsmkihwkocjAk8gnscGoHzhLozZouPJEU"
  NEXT_PUBLIC_IAMAI_MINT_ADDRESS = "5ieP1Z14NwuJpWeanJWXLKBENwNzqMvXkwdLEC5kpfbu"
